export const COMMENT_TEMPLATE = `## 🎯 Helm Chart Rendered

### Values Used
<details>
<summary>Click to expand values</summary>

\`\`\`yaml
{{valuesUsed}}
\`\`\`
</details>

### Rendered Output
<details>
<summary>Click to expand rendered chart ({{lineCount}} lines)</summary>

\`\`\`yaml
{{helmOutput}}
\`\`\`
</details>

---
*Generated by Rudder GitHub Action*
`;
